import { expect, test, type Page } from "@playwright/test"

test.skip(process.env.DAOYUN_LOCAL_E2E !== "1", "Requires the seeded local API and demo admin account")

test("admin workspaces separate browsing, editing, and dialogs at every supported width", async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  page.on("pageerror", (error) => errors.push(error.message))
  await page.goto("/")
  await page.getByRole("button", { name: "登录", exact: true }).first().click()
  await page.locator("#auth-identifier").fill("demo_admin")
  await page.locator("#auth-password").fill("DaoYunLocalOnly!2026")
  await page.locator('[role="dialog"] button[type="submit"]').click()
  await expect(page.getByRole("dialog")).toHaveCount(0)

  for (const width of testInfo.project.name.includes("mobile") ? [320, 768] : [1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto("/#admin/users")
    const member = page.getByRole("button", { name: "本地测试成员 @demo_member", exact: true })
    await expect(member).toBeVisible()
    await fitsViewport(page)
    await member.click()
    await expect(page.getByRole("dialog", { name: "用户速览" })).toBeVisible()
    await expect(page.getByLabel("操作原因", { exact: true })).toHaveCount(0)
    await page.getByRole("button", { name: "管理账号状态", exact: true }).click()
    const statusDialog = page.getByRole("dialog", { name: "管理账号状态", exact: true })
    await expect(statusDialog).toBeVisible()
    await fitsViewport(page)
    await expect(statusDialog).toBeInViewport({ ratio: 0.95 })
    await statusDialog.getByLabel("操作原因", { exact: true }).fill("界面回归核查，仅检查确认步骤")
    await statusDialog.getByRole("button", { name: "确认提交" }).click()
    await expect(page.getByRole("alertdialog")).toBeVisible()
    await page.keyboard.press("Escape")
    await expect(page.getByRole("alertdialog")).toHaveCount(0)
    await expect(statusDialog.getByRole("button", { name: "确认提交" })).toBeFocused()
    await page.keyboard.press("Escape")
    await expect(statusDialog).toHaveCount(0)
    await page.getByRole("button", { name: "调整角色", exact: true }).click()
    await expect(page.getByRole("dialog", { name: "调整角色", exact: true })).toBeVisible()
    await fitsViewport(page)
    await page.keyboard.press("Escape")
    await page.keyboard.press("Escape")
    await expect(member).toBeFocused()
    await expect(page.locator("body")).not.toHaveCSS("overflow", "hidden")

    await page.goto("/#admin/authorization")
    await page.getByRole("button", { name: "新建角色", exact: true }).click()
    await expect(page.getByLabel("角色键")).toBeVisible()
    await expect(page.locator(".authorization-role-list")).toHaveCount(0)
    await fitsViewport(page)
    await page.getByRole("button", { name: "返回角色目录" }).click()
    await page.getByRole("button", { name: "人员授权", exact: true }).click()
    await expect(page.getByLabel("用户名（精确匹配）")).toHaveCount(0)
    await page.getByRole("button", { name: "新增授权" }).click()
    await expect(page.getByRole("dialog", { name: "分配角色" })).toBeVisible()
    await fitsViewport(page)
    await page.keyboard.press("Escape")

    await page.goto("/#admin/plugins")
    await page.getByRole("button", { name: "安装插件", exact: true }).click()
    await page.getByLabel("插件键", { exact: true }).fill("interface_check")
    await fitsViewport(page)
    await page.keyboard.press("Escape")
    await page.getByRole("button", { name: "安装插件", exact: true }).click()
    await expect(page.getByLabel("插件键", { exact: true })).toHaveValue("interface_check")
    await page.keyboard.press("Escape")

    await page.goto("/#admin/operations")
    await page.getByRole("button", { name: "告警规则", exact: true }).click()
    await expect(page.locator(".operations-rule input")).toHaveCount(0)
    await page.getByRole("button", { name: /^编辑 .+规则$/ }).first().click()
    await expect(page.getByRole("dialog", { name: "编辑告警规则" })).toBeVisible()
    await fitsViewport(page)
    await page.keyboard.press("Escape")

    await page.goto("/#admin/branding")
    await page.getByLabel("站点名称", { exact: true }).fill("界面核查草稿")
    await page.getByRole("button", { name: "主题外观", exact: true }).click()
    await expect(page.getByLabel("主色", { exact: true })).toBeVisible()
    await fitsViewport(page)
    await page.getByRole("button", { name: "基本信息", exact: true }).click()
    await expect(page.getByLabel("站点名称", { exact: true })).toHaveValue("界面核查草稿")

    await page.goto("/#admin/email")
    await page.getByRole("button", { name: "测试发信", exact: true }).click()
    await expect(page.getByRole("dialog", { name: "测试发信" })).toBeVisible()
    await fitsViewport(page)
    await page.keyboard.press("Escape")

    await page.goto("/#admin/risk")
    await page.getByRole("button", { name: "自动治理策略", exact: true }).click()
    await expect(page.getByRole("dialog", { name: "自动治理策略" })).toBeVisible()
    await fitsViewport(page)
    await page.keyboard.press("Escape")

    for (const module of ["dashboard", "reports", "boards", "membership", "moderation"]) {
      await page.goto(`/#admin/${module}`)
      await expect(page.locator(".system-admin-page-heading h1")).toBeVisible()
      await expect(page.locator(".admin-state").filter({ hasText: /正在/ })).toHaveCount(0)
      await fitsViewport(page)
    }
    await page.goto("/#admin/users")
    await expect(member).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath(`admin-users-${width}.png`), fullPage: true })
    await member.click()
    await page.getByRole("button", { name: "管理账号状态", exact: true }).click()
    await page.screenshot({ path: testInfo.outputPath(`admin-status-${width}.png`), fullPage: true })
    await page.keyboard.press("Escape")
    await page.keyboard.press("Escape")
  }
  expect(errors).toEqual([])
})

async function fitsViewport(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true)
}

test("focused governance workspaces preserve drafts and dialog focus", async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  page.on("pageerror", (error) => errors.push(error.message))
  await page.goto("/")
  await page.getByRole("button", { name: "登录", exact: true }).first().click()
  await page.locator("#auth-identifier").fill("demo_admin")
  await page.locator("#auth-password").fill("DaoYunLocalOnly!2026")
  await page.locator('[role="dialog"] button[type="submit"]').click()
  await expect(page.getByRole("dialog")).toHaveCount(0)

  for (const width of testInfo.project.name.includes("mobile") ? [320, 768] : [1024, 1440]) {
    await page.setViewportSize({ width, height: 960 })
    await page.goto("/#admin/boards")
    const boardMenu = page.getByRole("button", { name: /^更多操作：/ }).first()
    await boardMenu.click()
    await page.getByRole("menuitem", { name: "编辑设置", exact: true }).click()
    const boardDialog = page.getByRole("dialog")
    await expect(boardDialog).toBeVisible()
    await expect.poll(() => boardDialog.evaluate((element) => element.contains(document.activeElement))).toBe(true)
    await boardDialog.getByLabel("版块名称", { exact: true }).fill("未保存的版块草稿")
    await boardDialog.getByRole("button", { name: "外观展示", exact: true }).click()
    await boardDialog.getByRole("button", { name: "基本信息", exact: true }).click()
    await expect(boardDialog.getByLabel("版块名称", { exact: true })).toHaveValue("未保存的版块草稿")
    await boardDialog.getByRole("button", { name: "访问权限", exact: true }).click()
    await expect(boardDialog.getByLabel("访问策略匹配方式")).toBeVisible()
    await expect(page).toHaveURL(/#admin\/boards$/)
    await fitsViewport(page)
    await page.keyboard.press("Escape")
    await expect(boardDialog).toHaveCount(0)
    await expect(boardMenu).toBeFocused()

    await page.goto("/#admin/moderation")
    const topic = page.locator(".moderation-topic-row").first()
    const action = topic.getByRole("button", { name: /^操作：/ })
    await action.click()
    await topic.getByRole("menuitem", { name: "处理记录", exact: true }).click()
    const history = page.getByRole("dialog", { name: "主题处理记录" })
    await expect(history).toBeVisible()
    await fitsViewport(page)
    await page.keyboard.press("Escape")
    await expect(action).toBeFocused()
    await action.click()
    await topic.getByRole("menuitem", { name: "移动", exact: true }).click()
    const move = page.getByRole("dialog", { name: "移动主题" })
    await expect(move.getByRole("textbox", { name: "处理备注" })).toBeFocused()
    await fitsViewport(page)
    await page.keyboard.press("Escape")
    await expect(action).toBeFocused()

    await page.goto("/#admin/authorization")
    await page.getByRole("button", { name: /^查看权限：/ }).first().click()
    await expect(page.getByLabel("角色名称", { exact: true })).toBeDisabled()
    await expect(page.getByRole("button", { name: "保存角色", exact: true })).toHaveCount(0)
    await page.getByRole("button", { name: "返回角色目录" }).click()
    await page.getByRole("button", { name: "新建角色", exact: true }).click()
    const permissions = page.locator(".authorization-permission-grid")
    const firstPermission = permissions.getByRole("checkbox").first()
    const permissionLabel = await firstPermission.getAttribute("aria-label")
    await firstPermission.check()
    await page.getByRole("navigation", { name: "权限分类" }).getByRole("button").last().click()
    await page.getByRole("searchbox", { name: "搜索权限" }).fill(permissionLabel!.split(" ").at(-1)!)
    await expect(page.getByRole("checkbox", { name: permissionLabel!, exact: true })).toBeChecked()
    await fitsViewport(page)
    await page.screenshot({ path: testInfo.outputPath(`focused-role-editor-${width}.png`) })
    await page.getByRole("button", { name: "返回角色目录" }).click()
    if (width === 320 || width === 1440) {
      await page.getByRole("button", { name: "切换为深色主题" }).click()
      for (const module of ["moderation", "boards", "authorization"]) {
        await page.goto(`/#admin/${module}`)
        await expect(page.locator(".admin-catalog")).toBeVisible()
        await fitsViewport(page)
      }
      await page.screenshot({ path: testInfo.outputPath(`focused-dark-${width}.png`) })
      await page.getByRole("button", { name: "切换为浅色主题" }).click()
    }
  }
  expect(errors).toEqual([])
})
