import { expect, test } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"

test.skip(process.env.DAOYUN_LOCAL_E2E !== "1", "Requires the seeded local API")

test("membership catalog supports real medal CRUD and responsive dialogs", async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto("/")
  await page.getByRole("button", { name: "登录", exact: true }).first().click()
  await page.locator("#auth-identifier").fill("demo_admin")
  await page.locator("#auth-password").fill("DaoYunLocalOnly!2026")
  await page.locator('[role="dialog"] button[type="submit"]').click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await page.goto("/#admin/membership")
  for (const width of testInfo.project.name.includes("mobile") ? [320, 768] : [1024, 1440]) {
    await page.setViewportSize({ width, height: 960 })
    for (const tab of ["成长运营", "积分运营", "勋章运营", "用户组", "标准权益"]) {
      await page.getByRole("tab", { name: tab, exact: true }).click()
      await expect(page.getByRole("tabpanel", { name: tab })).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
      if (tab === "成长运营") await page.screenshot({ path: testInfo.outputPath(`membership-growth-${width}.png`) })
    }
    await page.getByRole("tab", { name: "勋章运营" }).click()
    await expect(page.getByRole("list", { name: "勋章规则列表" })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath(`medal-catalog-${width}.png`) })
    const create = page.getByRole("button", { name: "新增勋章", exact: true })
    await create.click()
    const editor = page.getByRole("dialog", { name: "新增勋章" })
    await expect(editor.getByLabel("勋章名称")).toBeFocused()
    await expect(editor.getByRole("radio")).toHaveCount(0)
    await expect(editor.getByRole("img")).toHaveCount(0)
    await editor.getByLabel("上传自定义图标").setInputFiles("public/assets/membership/medals/medal1.gif")
    await expect(editor.getByRole("img", { name: "当前勋章图标预览" })).toHaveAttribute("src", /^blob:/)
    await editor.getByLabel("发放方式", { exact: true }).selectOption("automatic")
    await expect(editor.getByLabel("累计积分阈值")).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`medal-editor-${width}.png`) })
    if (width === 320 || width === 1440) {
      const result = await new AxeBuilder({ page }).include(".medal-editor").analyze()
      expect(result.violations, JSON.stringify(result.violations)).toEqual([])
    }
    await page.keyboard.press("Escape")
    await expect(editor).toHaveCount(0)
    await expect(create).toBeFocused()
    await page.getByRole("button", { name: "发放勋章", exact: true }).click()
    await expect(page.getByRole("dialog", { name: "发放勋章" }).getByRole("searchbox", { name: "搜索用户" })).toBeVisible()
    await page.keyboard.press("Escape")
    await page.getByRole("button", { name: "操作记录", exact: true }).click()
    await expect(page.getByRole("heading", { name: "操作记录", exact: true })).toBeVisible()
    await page.getByRole("button", { name: "勋章目录", exact: true }).click()
  }

  const name = `界面验收勋章-${testInfo.project.name}-${Date.now()}`
  await page.getByRole("button", { name: "新增勋章", exact: true }).click()
  await page.getByLabel("勋章名称").fill(name)
  await page.getByLabel("上传自定义图标").setInputFiles("public/assets/membership/medals/medal1.gif")
  await page.getByRole("button", { name: "创建勋章", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(page.getByRole("img", { name, exact: true })).toHaveAttribute("src", /^\/api\/v1\/membership\/medal-assets\/upload_[a-f0-9]{64}$/)
  const firstUrl = await page.getByRole("img", { name, exact: true }).getAttribute("src")
  await page.getByRole("button", { name: `编辑 ${name}`, exact: true }).click()
  await page.getByLabel("勋章名称").fill(`${name}-已编辑`)
  await expect(page.getByRole("img", { name: "当前勋章图标预览" })).toHaveAttribute("src", firstUrl!)
  await page.getByLabel("上传自定义图标").setInputFiles("public/assets/membership/medals/medal2.gif")
  await page.getByRole("button", { name: "保存勋章", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await page.reload()
  await page.getByRole("tab", { name: "勋章运营" }).click()
  await expect(page.getByRole("img", { name: `${name}-已编辑`, exact: true })).toBeVisible()
  await expect(page.getByRole("img", { name: `${name}-已编辑`, exact: true })).not.toHaveAttribute("src", firstUrl!)
  expect(await page.getByRole("img", { name: `${name}-已编辑`, exact: true }).evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
  const secondUrl = await page.getByRole("img", { name: `${name}-已编辑`, exact: true }).getAttribute("src")
  await page.getByRole("button", { name: `编辑 ${name}-已编辑`, exact: true }).click()
  await page.getByRole("button", { name: "保存勋章", exact: true }).click()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(page.getByRole("img", { name: `${name}-已编辑`, exact: true })).toHaveAttribute("src", secondUrl!)
  await page.getByRole("button", { name: `删除 ${name}-已编辑`, exact: true }).click()
  const confirmation = page.getByRole("alertdialog", { name: "删除勋章" })
  await expect(confirmation).toContainText("成员已持有的勋章与历史记录会保留")
  await confirmation.getByRole("button", { name: "确认删除", exact: true }).click()
  await expect(confirmation).toHaveCount(0)
  await expect(page.getByRole("img", { name: `${name}-已编辑`, exact: true })).toHaveCount(0)
  await page.getByRole("button", { name: "切换为深色主题" }).click()
  await page.screenshot({ path: testInfo.outputPath("medal-catalog-dark.png") })
  expect(errors).toEqual([])
})
