export interface PollInput {question:string;options:string[];ends_at:string}
export interface TopicPoll {topic_id:string;question:string;ends_at:string;revision:number;enabled:boolean;closed:boolean;can_vote:boolean;can_edit:boolean;selected_option:string|null;total_votes:number|null;options:{id:string;label:string;votes:number|null}[]}
export interface PollPolicy {enabled:boolean;can_create:boolean}
export class PollApiError extends Error {constructor(public status:number,public code:string,message:string){super(message)}}
const object=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==="object"&&!Array.isArray(v)
const uuid=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)
const count=(v:unknown):v is number=>typeof v==="number"&&Number.isSafeInteger(v)&&v>=0
function poll(v:unknown):v is TopicPoll|null{return v===null||object(v)&&uuid(v.topic_id)&&typeof v.question==="string"&&typeof v.ends_at==="string"&&Number.isFinite(Date.parse(v.ends_at))&&count(v.revision)&&v.revision>0&&[v.enabled,v.closed,v.can_vote,v.can_edit].every(b=>typeof b==="boolean")&&(v.selected_option===null||uuid(v.selected_option))&&(v.total_votes===null||count(v.total_votes))&&Array.isArray(v.options)&&v.options.length>=2&&v.options.length<=10&&v.options.every(o=>object(o)&&uuid(o.id)&&typeof o.label==="string"&&(o.votes===null||count(o.votes)))}
async function request<T>(path:string,guard:(v:unknown)=>v is T,init:RequestInit={}):Promise<T>{const response=await fetch(path,{credentials:"include",...init});const payload:unknown=await response.json().catch(()=>null);if(!response.ok){const e=object(payload)&&object(payload.error)?payload.error:{};throw new PollApiError(response.status,String(e.code??"response.invalid"),String(e.message??"投票请求失败"))}if(!object(payload)||!object(payload.meta)||!uuid(payload.meta.request_id)||!guard(payload.data))throw new Error("投票响应格式无效");return payload.data}
export function getPollPolicy(signal?:AbortSignal){return request("/api/v1/polls/policy",(v):v is PollPolicy=>object(v)&&typeof v.enabled==="boolean"&&typeof v.can_create==="boolean",{signal})}
export function getTopicPoll(topicId:string,signal?:AbortSignal){return request("/api/v1/topics/"+encodeURIComponent(topicId)+"/poll",poll,{signal})}
export function voteTopicPoll(topicId:string,optionId:string,csrfToken:string){return request("/api/v1/topics/"+encodeURIComponent(topicId)+"/poll/votes",poll,{method:"POST",headers:{"Content-Type":"application/json","x-csrf-token":csrfToken},body:JSON.stringify({option_id:optionId})})}
export function updateTopicPoll(topicId:string,revision:number,input:PollInput,csrfToken:string){return request("/api/v1/topics/"+encodeURIComponent(topicId)+"/poll",poll,{method:"PUT",headers:{"Content-Type":"application/json","x-csrf-token":csrfToken},body:JSON.stringify({expected_revision:revision,poll:input})})}

export function isPollInput(v:unknown):v is PollInput{return object(v)&&typeof v.question==="string"&&Array.isArray(v.options)&&v.options.length>=2&&v.options.length<=10&&v.options.every(o=>typeof o==="string")&&typeof v.ends_at==="string"}
