import { cleanup, render, screen, waitFor, within } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { afterEach, beforeEach, expect, it, vi } from "vitest"
import { getAdminComment, listAdminComments, moderateAdminComment } from "../api/adminComments"
import { CommentAdminPanel } from "./CommentAdminPanel"
vi.mock("../api/adminComments", () => ({ getAdminComment: vi.fn(), listAdminComments: vi.fn(), moderateAdminComment: vi.fn() }))
const id = "019fc800-0000-7000-8000-000000000001"
const second = "019fc800-0000-7000-8000-000000000002"
const boards = [{ id, slug: "general", name: "交流", tone: "blue" as const, capabilityKeys: ["moderation.topic"] }]
const comment = { id, topic_id: id, topic_title: "原帖", board_id: id, board_name: "交流",
  author: { id, username: "member", display_name: "成员", avatar_url: null },
  content: "需要核查的评论", content_truncated: true, status: "published" as const, created_at: "2026-09-22T00:00:00Z", updated_at: "2026-09-22T00:00:00Z" }
beforeEach(() => {
  vi.mocked(listAdminComments).mockResolvedValue({ comments: [comment], nextCursor: null })
  vi.mocked(getAdminComment).mockResolvedValue({ ...comment, content: "评论完整正文", content_truncated: false })
  vi.mocked(moderateAdminComment).mockResolvedValue({ ...comment, status: "hidden", content_truncated: false })
})
afterEach(() => { cleanup(); vi.resetAllMocks(); vi.unstubAllGlobals() })
it("loads full content and requires a reason before hiding a comment", async () => {
  const user = userEvent.setup()
  render(<CommentAdminPanel boards={boards} csrfToken="csrf" />)
  await user.click(await screen.findByRole("button", { name: "查看评论：成员" }))
  const dialog = await screen.findByRole("dialog", { name: "评论详情" })
  expect(await within(dialog).findByText("评论完整正文")).toBeInTheDocument()
  await user.click(within(dialog).getByRole("button", { name: "隐藏评论" }))
  expect(within(dialog).getByRole("button", { name: "确认隐藏" })).toBeDisabled()
  await user.type(within(dialog).getByLabelText("处理说明"), "垃圾广告")
  await user.click(within(dialog).getByRole("button", { name: "确认隐藏" }))
  await waitFor(() => expect(moderateAdminComment).toHaveBeenCalledWith(id, { status: "hidden", expected_updated_at: comment.updated_at, reason: "垃圾广告" }, "csrf"))
  expect(await within(dialog).findByRole("button", { name: "恢复评论" })).toBeInTheDocument()
})
it("loads more and resets the queue when the status changes", async () => {
  vi.mocked(listAdminComments).mockResolvedValueOnce({ comments: [comment], nextCursor: id })
    .mockResolvedValueOnce({ comments: [{ ...comment, id: second, content: "第二条评论" }], nextCursor: null })
    .mockResolvedValue({ comments: [], nextCursor: null })
  const user = userEvent.setup()
  render(<CommentAdminPanel boards={boards} csrfToken="csrf" />)
  await user.click(await screen.findByRole("button", { name: "加载更多评论" }))
  expect(await screen.findByText("第二条评论")).toBeInTheDocument()
  expect(listAdminComments).toHaveBeenNthCalledWith(2, expect.objectContaining({ cursor: id, boardId: id }))
  await user.selectOptions(screen.getByLabelText("评论状态"), "hidden")
  expect(await screen.findByText("当前筛选下暂无评论")).toBeInTheDocument()
  expect(screen.queryByText("第二条评论")).not.toBeInTheDocument()
})
it("does not fetch without an authorized board and retries failed queues", async () => {
  const empty = render(<CommentAdminPanel boards={[]} csrfToken="csrf" />)
  expect(screen.getByText("当前账号没有可管理评论的版块")).toBeInTheDocument()
  expect(listAdminComments).not.toHaveBeenCalled()
  empty.unmount()
  vi.mocked(listAdminComments).mockRejectedValueOnce(new Error("读取失败"))
  render(<CommentAdminPanel boards={boards} csrfToken="csrf" />)
  expect(await screen.findByRole("alert")).toHaveTextContent("读取失败")
  await userEvent.setup().click(screen.getByRole("button", { name: "重试评论列表" }))
  expect(await screen.findByText("需要核查的评论")).toBeInTheDocument()
})

it("renders scoped statistics and a structured selectable comment table", async () => {
  const user = userEvent.setup()
  render(<CommentAdminPanel boards={boards} csrfToken="csrf" />)
  const table = await screen.findByRole("table", { name: "评论列表" })
  expect(within(table).getAllByRole("columnheader")).toHaveLength(7)
  expect(screen.getByRole("region", { name: "已加载评论统计" })).toHaveTextContent("涉及主题")
  await user.click(screen.getByRole("checkbox", { name: "选择当前评论" }))
  expect(screen.getByRole("button", { name: "导出选中 1 条摘要" })).toBeEnabled()
  await user.click(screen.getByRole("button", { name: "取消选择" }))
  expect(screen.getByRole("checkbox", { name: "选择当前评论" })).not.toBeChecked()
})
it("navigates through full comments and restores focus when closing", async () => {
  const user = userEvent.setup()
  vi.mocked(listAdminComments).mockResolvedValue({ comments: [comment, { ...comment, id: second, content: "第二条评论" }], nextCursor: null })
  vi.mocked(getAdminComment).mockImplementation(async (commentId) => ({ ...comment, id: commentId, content: commentId === id ? "第一条完整正文" : "第二条完整正文", content_truncated: false }))
  render(<CommentAdminPanel boards={boards} csrfToken="csrf" />)
  const trigger = (await screen.findAllByRole("button", { name: "查看评论：成员" }))[0]
  await user.click(trigger)
  const dialog = screen.getByRole("dialog", { name: "评论详情" })
  await within(dialog).findByText("第一条完整正文")
  expect(within(dialog).getByRole("button", { name: "上一条评论" })).toBeDisabled()
  await user.click(within(dialog).getByRole("button", { name: "下一条评论" }))
  await within(dialog).findByText("第二条完整正文")
  expect(within(dialog).getByRole("link", { name: /查看原帖/ })).toHaveAttribute("href", "#topic/" + id + "?reply=" + second)
  expect(within(dialog).getByRole("button", { name: "下一条评论" })).toBeDisabled()
  await user.keyboard("{Escape}")
  await waitFor(() => expect(trigger).toHaveFocus())
})
it("retries a failed next page without losing the current list", async () => {
  const user = userEvent.setup()
  vi.mocked(listAdminComments).mockResolvedValueOnce({ comments: [comment], nextCursor: second }).mockRejectedValueOnce(new Error("分页失败")).mockResolvedValueOnce({ comments: [{ ...comment, id: second, content: "第二条评论" }], nextCursor: null })
  render(<CommentAdminPanel boards={boards} csrfToken="csrf" />)
  await user.click(await screen.findByRole("button", { name: "加载更多评论" }))
  expect(await screen.findByRole("alert")).toHaveTextContent("分页失败")
  expect(screen.getByText(comment.content)).toBeInTheDocument()
  await user.click(screen.getByRole("button", { name: "加载更多评论" }))
  expect(await screen.findByText("第二条评论")).toBeInTheDocument()
})
it("resets date filtering and reloads from the beginning when changing page size", async () => {
  const user = userEvent.setup()
  vi.mocked(listAdminComments).mockResolvedValue({ comments: [{ ...comment, created_at: new Date(Date.now() - 90 * 86400000).toISOString() }], nextCursor: null })
  render(<CommentAdminPanel boards={boards} csrfToken="csrf" />)
  await screen.findByText(comment.content)
  await user.selectOptions(screen.getByRole("combobox", { name: "评论发布时间" }), "7")
  expect(screen.queryByText(comment.content)).not.toBeInTheDocument()
  await user.click(screen.getByRole("button", { name: "重置" }))
  await screen.findByText(comment.content)
  await user.selectOptions(screen.getByRole("combobox", { name: "每次加载评论条数" }), "50")
  await waitFor(() => expect(listAdminComments).toHaveBeenLastCalledWith(expect.objectContaining({ limit: 50, cursor: null })))
})

it("uses a modal drawer on desktop and keeps keyboard focus after moderation", async () => {
  vi.stubGlobal("matchMedia", () => ({ matches: true, addEventListener: vi.fn(), removeEventListener: vi.fn() }))
  const user = userEvent.setup()
  render(<CommentAdminPanel boards={boards} csrfToken="csrf" />)
  const trigger = await screen.findByRole("button", { name: "查看评论：成员" })
  await user.click(trigger)
  const dialog = screen.getByRole("dialog", { name: "评论详情" })
  expect(dialog).toHaveAttribute("aria-modal", "true")
  expect(document.body.style.overflow).toBe("hidden")
  await user.click(await within(dialog).findByRole("button", { name: "隐藏评论" }))
  await user.type(within(dialog).getByLabelText("处理说明"), "重复内容")
  await user.click(within(dialog).getByRole("button", { name: "确认隐藏" }))
  await within(dialog).findByText("评论已隐藏")
  expect(dialog).toContainElement(document.activeElement as HTMLElement)
  await user.keyboard("{Escape}")
  await waitFor(() => expect(trigger).toHaveFocus())
})

it("restores a moderated comment to its filtered list without reloading or duplicating rows", async () => {
  const user = userEvent.setup()
  vi.mocked(listAdminComments).mockResolvedValue({ comments: [comment, { ...comment, id: second, content: "较早评论", created_at: "2026-09-22T07:00:00+08:00" }], nextCursor: null })
  vi.mocked(moderateAdminComment).mockResolvedValueOnce({ ...comment, status: "hidden" }).mockResolvedValueOnce(comment)
  render(<CommentAdminPanel boards={boards} csrfToken="csrf" />)
  await screen.findByRole("table", { name: "评论列表" })
  await user.selectOptions(screen.getByLabelText("评论状态"), "published")
  await screen.findByText(comment.content)
  const fetchCount = vi.mocked(listAdminComments).mock.calls.length
  await user.click(screen.getAllByRole("button", { name: "查看评论：成员" })[0])
  const dialog = screen.getByRole("dialog", { name: "评论详情" })
  await user.click(await within(dialog).findByRole("button", { name: "隐藏评论" }))
  await user.type(within(dialog).getByLabelText("处理说明"), "核查内容")
  await user.click(within(dialog).getByRole("button", { name: "确认隐藏" }))
  await within(dialog).findByText("评论已隐藏")
  expect(within(screen.getByRole("table")).queryByText(comment.content)).not.toBeInTheDocument()
  await user.click(within(dialog).getByRole("button", { name: "恢复评论" }))
  await user.type(within(dialog).getByLabelText("处理说明"), "核查通过")
  await user.click(within(dialog).getByRole("button", { name: "确认恢复" }))
  await within(dialog).findByText("评论已恢复")
  const rows = within(screen.getByRole("table")).getAllByRole("row")
  expect(rows).toHaveLength(3)
  expect(rows[1]).toHaveTextContent(comment.content)
  expect(listAdminComments).toHaveBeenCalledTimes(fetchCount)
  await user.keyboard("{Escape}")
  await waitFor(() => expect(within(rows[1]).getByRole("button", { name: "查看评论：成员" })).toHaveFocus())
})
