import { describe, expect, it } from "vitest"
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"

import {
  DEFAULT_INPUT,
  DEFAULT_OUTPUT,
  generateApiClient,
  parseArguments,
} from "./generate-api-client.mjs"

describe("generate-api-client arguments", () => {
  it("uses the local OpenAPI endpoint and generated declaration path by default", () => {
    expect(parseArguments([])).toEqual({ input: DEFAULT_INPUT, output: DEFAULT_OUTPUT, check: false })
  })

  it("accepts explicit input and output paths", () => {
    expect(parseArguments([
      "--input",
      "C:/tmp/openapi.json",
      "--output",
      "src/api/generated.d.ts",
    ])).toEqual({ input: "C:/tmp/openapi.json", output: "src/api/generated.d.ts", check: false })
  })

  it("rejects unknown flags and non-declaration output files", () => {
    expect(() => parseArguments(["--unknown", "value"])).toThrow("未知参数")
    expect(() => parseArguments(["--output", "src/api/generated.ts"])).toThrow(".d.ts")
  })

  it("accepts a declaration consistency check flag", () => {
    expect(parseArguments(["--check"])).toEqual({
      input: DEFAULT_INPUT,
      output: DEFAULT_OUTPUT,
      check: true,
    })
  })

  it("generates UTF-8 declaration output from a local OpenAPI document", async () => {
    const directory = await mkdtemp(join(tmpdir(), "daoyun-openapi-"))
    const input = join(directory, "openapi.json")
    const output = join(directory, "generated.d.ts")
    await writeFile(input, JSON.stringify({
      openapi: "3.1.0",
      info: { title: "Test API", version: "1.0.0" },
      paths: {
        "/api/v1/health/live": {
          get: {
            responses: { "200": { description: "ok" } },
          },
        },
      },
    }), "utf8")

    try {
      await generateApiClient({ input, output })
      const generated = await readFile(output, "utf8")
      expect(generated).toContain("@generated by scripts/generate-api-client.mjs")
      expect(generated).toContain("/api/v1/health/live")
    } finally {
      await rm(directory, { recursive: true, force: true })
    }
  })

  it("checks an existing declaration without rewriting it", async () => {
    const directory = await mkdtemp(join(tmpdir(), "daoyun-openapi-check-"))
    const input = join(directory, "openapi.json")
    const output = join(directory, "generated.d.ts")
    await writeFile(input, JSON.stringify({
      openapi: "3.1.0",
      info: { title: "Test API", version: "1.0.0" },
      paths: {
        "/api/v1/health/live": {
          get: {
            responses: { "200": { description: "ok" } },
          },
        },
      },
    }), "utf8")

    try {
      await generateApiClient({ input, output })
      const before = await readFile(output, "utf8")
      await generateApiClient({ input, output, check: true })
      expect(await readFile(output, "utf8")).toBe(before)

      await writeFile(output, `${before}\n`, "utf8")
      await expect(generateApiClient({ input, output, check: true }))
        .rejects.toThrow("与 OpenAPI 文档不一致")
    } finally {
      await rm(directory, { recursive: true, force: true })
    }
  })
})
