UPDATE permissions AS permission
SET name = localized.name,
    description = localized.description,
    updated_at = CURRENT_TIMESTAMP
FROM (
    VALUES
        ('admin.configuration.read', 'Read administration configuration', 'Read protected administration configuration.'),
        ('admin.configuration.write', 'Write administration configuration', 'Change site branding and board configuration.'),
        ('admin.users.moderate', 'Moderate managed users', 'Restrict, suspend, and restore managed user accounts.'),
        ('admin.users.read', 'Read managed users', 'Search users and read their management context.'),
        ('attachment.cleanup', 'Clean attachment objects', 'Remove expired attachment metadata and orphaned local objects.'),
        ('attachment.create', 'Create attachments', 'Create pending attachment metadata for an owned topic.'),
        ('audit.read', 'Read administration audit', 'Read immutable administration audit records.'),
        ('authorization.assignments.read', 'Read role assignments', 'Read user role assignments and their scopes.'),
        ('authorization.assignments.write', 'Manage role assignments', 'Grant and revoke custom role assignments.'),
        ('authorization.roles.read', 'Read authorization roles', 'Read the role and permission catalog.'),
        ('authorization.roles.write', 'Manage authorization roles', 'Create, update, and delete custom roles.'),
        ('community.groups.read', 'Read community groups', 'Read community group permission and quota configuration.'),
        ('community.groups.write', 'Write community groups', 'Create and update community group permission and quota configuration.'),
        ('community.memberships.read', 'Read community memberships', 'Read user community group memberships.'),
        ('community.memberships.write', 'Write community memberships', 'Grant and revoke user community group memberships.'),
        ('content.access_policies.read', '读取内容访问策略', '查看内容访问策略及主体'),
        ('content.access_policies.write', '管理内容访问策略', '创建和修改内容访问策略'),
        ('entitlements.grants.read', 'Read user entitlements', 'Read user standard entitlement projections.'),
        ('entitlements.grants.write', 'Write user entitlements', 'Grant and revoke user standard entitlement projections.'),
        ('entitlements.types.read', 'Read entitlement types', 'Read versioned standard entitlement types.'),
        ('entitlements.types.write', 'Write entitlement types', 'Publish standard entitlement type versions.'),
        ('governance.alerts.read', 'Read risk alerts', 'Read automated governance risk alerts.'),
        ('governance.alerts.resolve', 'Resolve risk alerts', 'Acknowledge or dismiss risk alerts.'),
        ('governance.policy.read', 'Read governance policy', 'Read automated governance thresholds.'),
        ('governance.policy.write', 'Write governance policy', 'Change automated governance thresholds.'),
        ('governance.reports.read', 'Read content reports', 'Read the moderation report queue.'),
        ('governance.reports.resolve', 'Resolve content reports', 'Resolve reports and apply moderation actions.'),
        ('membership.medals.grant', 'Grant membership medals', 'Grant or revoke medals for users.'),
        ('membership.medals.read', 'Read membership medals', 'Read medal ownership and operating rules.'),
        ('membership.medals.rules.write', 'Write membership medal rules', 'Change automatic medal award rules.'),
        ('membership.points.grant', 'Grant membership points', 'Grant points to membership accounts.'),
        ('membership.rules.read', 'Read membership rules', 'Read configured membership level thresholds.'),
        ('membership.rules.write', 'Write membership rules', 'Change membership level thresholds.'),
        ('moderation.topic', 'Moderate topics', 'Approve, hide, or reject topics.'),
        ('moderation.topic.feature', 'Feature topics', 'Feature and unfeature topics within an authorized board scope.'),
        ('moderation.topic.lock', 'Lock topics', 'Lock and unlock topics within an authorized board scope.'),
        ('moderation.topic.move', 'Move topics', 'Move topics between authorized board scopes.'),
        ('moderation.topic.pin', 'Pin topics', 'Pin and unpin topics within an authorized board scope.'),
        ('moderation.user.restrict_in_scope', 'Restrict users in board scope', 'Create and update temporary user posting restrictions in an authorized board scope.'),
        ('operations.alerts.write', 'Manage operations alerts', 'Update operational alert rules and acknowledge alert incidents.'),
        ('operations.read', 'Read operations monitoring', 'Read operational summaries, alert rules, and alert incidents.'),
        ('plugins.install', 'Install plugins', 'Install validated WebAssembly Component plugins.'),
        ('plugins.invoke', 'Invoke plugins', 'Invoke enabled plugins through declared capabilities.'),
        ('plugins.lifecycle', 'Manage plugin lifecycle', 'Enable, disable, and uninstall plugins.'),
        ('plugins.read', 'Read plugins', 'Read installed plugin metadata and lifecycle state.')
) AS localized(permission_key, name, description)
WHERE permission.permission_key = localized.permission_key;
