UPDATE permissions AS permission
SET name = localized.name,
    description = localized.description,
    updated_at = CURRENT_TIMESTAMP
FROM (
    VALUES
        ('admin.configuration.read', '读取管理配置', '查看受保护的管理配置。'),
        ('admin.configuration.write', '管理站点配置', '修改站点品牌与板块配置。'),
        ('admin.users.moderate', '管理用户状态', '限制、暂停或恢复用户账号。'),
        ('admin.users.read', '查看用户', '搜索用户并查看用户管理信息。'),
        ('attachment.cleanup', '清理附件对象', '清理过期附件元数据及本地孤立对象。'),
        ('attachment.create', '创建附件', '为自己拥有的主题创建待处理附件元数据。'),
        ('audit.read', '读取管理审计', '查看不可变的管理审计记录。'),
        ('authorization.assignments.read', '读取角色分配', '查看用户角色分配及其作用域。'),
        ('authorization.assignments.write', '管理角色分配', '授予或撤销自定义角色分配。'),
        ('authorization.roles.read', '读取授权角色', '查看角色与权限目录。'),
        ('authorization.roles.write', '管理授权角色', '创建、更新或删除自定义角色。'),
        ('community.groups.read', '读取社区组', '查看社区组权限与配额配置。'),
        ('community.groups.write', '管理社区组', '创建和更新社区组权限与配额配置。'),
        ('community.memberships.read', '读取社区组成员', '查看用户所属的社区组。'),
        ('community.memberships.write', '管理社区组成员', '授予或撤销用户的社区组成员资格。'),
        ('content.access_policies.read', '读取内容访问策略', '查看内容访问策略及其主体。'),
        ('content.access_policies.write', '管理内容访问策略', '创建和修改内容访问策略。'),
        ('entitlements.grants.read', '读取用户权益', '查看用户标准权益投影。'),
        ('entitlements.grants.write', '管理用户权益', '授予或撤销用户标准权益投影。'),
        ('entitlements.types.read', '读取权益类型', '查看版本化的标准权益类型。'),
        ('entitlements.types.write', '管理权益类型', '发布标准权益类型版本。'),
        ('governance.alerts.read', '读取风险告警', '查看自动化治理风险告警。'),
        ('governance.alerts.resolve', '处理风险告警', '确认或忽略风险告警。'),
        ('governance.policy.read', '读取治理策略', '查看自动化治理阈值。'),
        ('governance.policy.write', '管理治理策略', '修改自动化治理阈值。'),
        ('governance.reports.read', '读取内容举报', '查看内容审核举报队列。'),
        ('governance.reports.resolve', '处理内容举报', '处理举报并执行审核操作。'),
        ('membership.medals.grant', '管理会员勋章', '为用户授予或撤销勋章。'),
        ('membership.medals.read', '读取会员勋章', '查看勋章持有情况与运营规则。'),
        ('membership.medals.rules.write', '管理勋章规则', '修改自动授予勋章的规则。'),
        ('membership.points.grant', '授予会员积分', '为会员账户授予积分。'),
        ('membership.rules.read', '读取会员规则', '查看已配置的会员等级阈值。'),
        ('membership.rules.write', '管理会员规则', '修改会员等级阈值。'),
        ('moderation.topic', '审核主题', '审核、隐藏或驳回主题。'),
        ('moderation.topic.feature', '推荐主题', '在授权的板块作用域内推荐或取消推荐主题。'),
        ('moderation.topic.lock', '锁定主题', '在授权的板块作用域内锁定或解锁主题。'),
        ('moderation.topic.move', '移动主题', '在授权的板块作用域之间移动主题。'),
        ('moderation.topic.pin', '置顶主题', '在授权的板块作用域内置顶或取消置顶主题。'),
        ('moderation.user.restrict_in_scope', '限制板块内用户', '在授权的板块作用域内创建和更新临时发帖限制。'),
        ('operations.alerts.write', '管理运维告警', '更新运维告警规则并确认告警事件。'),
        ('operations.read', '读取运维监控', '查看运维摘要、告警规则及告警事件。'),
        ('plugins.install', '安装插件', '安装经过验证的 WebAssembly Component 插件。'),
        ('plugins.invoke', '调用插件', '通过声明的能力调用已启用的插件。'),
        ('plugins.lifecycle', '管理插件生命周期', '启用、停用或卸载插件。'),
        ('plugins.read', '读取插件', '查看已安装插件的元数据与生命周期状态。')
) AS localized(permission_key, name, description)
WHERE permission.permission_key = localized.permission_key;
